{:fennel-path "./?.fnl;./?/init.fnl;src/?.fnl;src/?/init.fnl"
 :macro-path "./?.fnlm;./?/init.fnlm;./?.fnl;./?/init-macros.fnl;./?/init.fnl;src/?.fnlm;src/?/init.fnlm;src/?.fnl;src/?/init-macros.fnl;src/?/init.fnl"
 :lua-version "lua5.1"
 :libraries { "/home/ictye/.config/nvim"
              "/home/ictye/.local/share/nvim/lazy/lazy.nvim"
              "/home/ictye/.local/share/nvim/lazy/lensline.nvim"
              "/home/ictye/.local/share/nvim/lazy/nvim-surround"
              "/home/ictye/.local/share/nvim/lazy/resession.nvim"
              "/home/ictye/.local/share/nvim/lazy/vim-smoothie"
              "/home/ictye/.local/share/nvim/lazy/flash.nvim"
              "/home/ictye/.local/share/nvim/lazy/bufferline.nvim"
              "/home/ictye/.local/share/nvim/lazy/neo-tree.nvim"
              "/home/ictye/.local/share/nvim/lazy/edgy.nvim"
              "/home/ictye/.local/share/nvim/lazy/neotest-vstest"
              "/home/ictye/.local/share/nvim/lazy/FixCursorHold.nvim"
              "/home/ictye/.local/share/nvim/lazy/neotest"
              "/home/ictye/.local/share/nvim/lazy/marks.nvim"
              "/home/ictye/.local/share/nvim/lazy/render-markdown.nvim"
              "/home/ictye/.local/share/nvim/lazy/img-clip.nvim"
              "/home/ictye/.local/share/nvim/lazy/copilot.lua"
              "/home/ictye/.local/share/nvim/lazy/fzf-lua"
              "/home/ictye/.local/share/nvim/lazy/telescope-fzf-native.nvim"
              "/home/ictye/.local/share/nvim/lazy/telescope.nvim"
              "/home/ictye/.local/share/nvim/lazy/mini.pick"
              "/home/ictye/.local/share/nvim/lazy/dressing.nvim"
              "/home/ictye/.local/share/nvim/lazy/avante.nvim"
              "/home/ictye/.local/share/nvim/lazy/nvim-dap-ui"
              "/home/ictye/.local/share/nvim/lazy/nvim-ufo"
              "/home/ictye/.local/share/nvim/lazy/vim-illuminate"
              "/home/ictye/.local/share/nvim/lazy/promise-async"
              "/home/ictye/.local/share/nvim/lazy/refactoring.nvim"
              "/home/ictye/.local/share/nvim/lazy/project_toolchain.nvim"
              "/home/ictye/.local/share/nvim/lazy/indent-blankline.nvim"
              "/home/ictye/.local/share/nvim/lazy/nvim-highlight-colors"
              "/home/ictye/.local/share/nvim/lazy/rainbow-delimiters.nvim"
              "/home/ictye/.local/share/nvim/lazy/todo-comments.nvim"
              "/home/ictye/.local/share/nvim/lazy/auto-pairs"
              "/home/ictye/.local/share/nvim/lazy/codewindow.nvim"
              "/home/ictye/.local/share/nvim/lazy/nvim-dap-virtual-text"
              "/home/ictye/.local/share/nvim/lazy/nvim-treesitter-context"
              "/home/ictye/.local/share/nvim/lazy/which-key.nvim"
              "/home/ictye/.local/share/nvim/lazy/dashboard-nvim"
              "/home/ictye/.local/share/nvim/lazy/hydra.nvim"
              "/home/ictye/.local/share/nvim/lazy/parsley"
              "/home/ictye/Projects/nvlime"
              "/home/ictye/.local/share/nvim/lazy/none-ls.nvim"
              "/home/ictye/.local/share/nvim/lazy/kitty-navigator.nvim"
              "/home/ictye/.local/share/nvim/lazy/firenvim"
              "/home/ictye/.local/share/nvim/lazy/nvim-unity-sync"
              "/home/ictye/.local/share/nvim/lazy/sonicpi.nvim"
              "/home/ictye/.local/share/nvim/lazy/fcitx5.nvim"
              "/home/ictye/.local/share/nvim/lazy/haskell-tools.nvim"
              "/home/ictye/.local/share/nvim/lazy/nvim-nio"
              "/home/ictye/.local/share/nvim/lazy/lua-utils.nvim"
              "/home/ictye/.local/share/nvim/lazy/neorg"
              "/home/ictye/.local/share/nvim/lazy/rustaceanvim"
              "/home/ictye/.local/share/nvim/lazy/screenkey.nvim"
              "/home/ictye/.local/share/nvim/lazy/blink.compat"
              "/home/ictye/.local/share/nvim/lazy/LuaSnip"
              "/home/ictye/.local/share/nvim/lazy/blink-cmp-avante"
              "/home/ictye/.local/share/nvim/lazy/colorful-menu.nvim"
              "/home/ictye/.local/share/nvim/lazy/friendly-snippets"
              "/home/ictye/.local/share/nvim/lazy/blink.cmp"
              "/home/ictye/.local/share/nvim/lazy/nvim-cmp"
              "/home/ictye/.local/share/nvim/lazy/minuet-ai.nvim"
              "/home/ictye/.local/share/nvim/lazy/mcphub.nvim"
              "/home/ictye/.local/share/nvim/lazy/pathlib.nvim"
              "/home/ictye/.local/share/nvim/lazy/nvim-web-devicons"
              "/home/ictye/.local/share/nvim/lazy/oil.nvim"
              "/home/ictye/.local/share/nvim/lazy/tree-sitter-norg-meta"
              "/home/ictye/.local/share/nvim/lazy/mini.nvim"
              "/home/ictye/.local/share/nvim/lazy/nvim-treesitter"
              "/home/ictye/.local/share/nvim/lazy/rest.nvim"
              "/home/ictye/.local/share/nvim/lazy/plenary.nvim"
              "/home/ictye/.local/share/nvim/lazy/claude-code.nvim"
              "/home/ictye/.local/share/nvim/lazy/tree-sitter-norg"
              "/home/ictye/.local/share/nvim/lazy/gitsigns.nvim"
              "/home/ictye/.local/share/nvim/lazy/nvim-navic"
              "/home/ictye/.local/share/nvim/lazy/nvim-dap"
              "/home/ictye/.local/share/nvim/lazy/overseer.nvim"
              "/home/ictye/.local/share/nvim/lazy/multicursor.nvim"
              "/home/ictye/.local/share/nvim/lazy/snacks.nvim"
              "/home/ictye/.local/share/nvim/lazy/opencode.nvim"
              "/home/ictye/.local/share/nvim/lazy/nvim-notify"
              "/home/ictye/.local/share/nvim/lazy/nui.nvim"
              "/home/ictye/.local/share/nvim/lazy/noice.nvim"
              "/home/ictye/.local/share/nvim/lazy/lualine.nvim"
              "/home/ictye/.local/share/nvim/lazy/vim-wakatime"
              "/home/ictye/.local/share/nvim/lazy/neogen"
              "/home/ictye/.local/share/nvim/lazy/catppuccin"
              "/usr/share/nvim/runtime"
              "/usr/share/nvim/runtime/pack/dist/opt/matchit"
              "/usr/lib64/nvim"
              "/home/ictye/.local/share/nvim/lazy/indent-blankline.nvim/after"
              "/home/ictye/Projects/nvlime/after"
              "/home/ictye/.local/share/nvim/lazy/sonicpi.nvim/after"
              "/home/ictye/.local/share/nvim/lazy/catppuccin/after"
              "/home/ictye/.config/nvim/after"
              "/home/ictye/.local/state/nvim/lazy/readme" }
 :extra-globals ""
 :lints {:unused-definition true
         :unknown-module-field true
         :unnecessary-method true
         :unnecessary-tset true
         :unnecessary-do true
         :redundant-do true
         :match-should-case true
         :bad-unpack true
         :var-never-set true
         :op-with-no-arguments true
         :multival-in-middle-of-call true
         :no-decreasing-comparison false}
}
